language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - SIMPHONY_VERSION=master PARAVIEW=paraview
  - SIMPHONY_VERSION=master PARAVIEW=paraviewopenfoam410
  - SIMPHONY_VERSION=0.6.0 PARAVIEW=paraview
  - SIMPHONY_VERSION=0.6.0 PARAVIEW=paraviewopenfoam410
matrix:
    allow_failures:
        - env: SIMPHONY_VERSION=master PARAVIEW=paraview
        - env: SIMPHONY_VERSION=master PARAVIEW=paraviewopenfoam410
before_install:
  - sudo sh -c "echo deb http://www.openfoam.org/download/ubuntu precise main > /etc/apt/sources.list.d/openfoam.list"
  - sudo apt-get update -qq
  # cloud init requires additional user input which halts the travis build.
  - sudo apt-mark hold cloud-init postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4
  # The upgrade can produce errors (e.g. with multiple postgres versions). 
  # Travis used to ignore them but now it doesn't, so we add a || true
  - sudo apt-get upgrade -y --force-yes -o Dpkg::Options::="--force-confold" 
  - sudo apt-get install -y --force-yes ${PARAVIEW} python-imaging 
  - pip install -r dev-requirements.txt
  - pip install -r test-requirements.txt
  - pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
install:
  - python setup.py develop
before_script:
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x768x24
  - if [[ $PARAVIEW == "paraviewopenfoam410" ]]; then source ./setup_openfoamparaview.sh; fi
script:
  - flake8 .
  - coverage run -m unittest discover -v
after_success:
  - pip install codecov
  - codecov
